spring:
  datasource:
    url: jdbc:mysql://localhost:3306/placeholder
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "placeholder"
    password: "placeholder"
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
